import "./globals.css";
import UiComponentProvider from "../components/Providers/UiComponentProvider";
import Header from "../components/Shared/Header/Header";
import Footer from "../components/Shared/Footer/Footer";
import { roboto, liAdor } from "@/src/utils/Fonts/Fonts.js";
import DarkThemeProvider from "../components/Providers/DarkThemeProvider";
import TanstackQueryProvider from "../components/Providers/TanstackQueryProvider";
import AuthContextProviders from "../context/AuthContextProviders";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: "Driving Shihun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${roboto.variable} ${liAdor.variable}`}
    >
      <body className="dark:bg-[#161C48]">
        <TanstackQueryProvider>
          <AuthContextProviders>
            <DarkThemeProvider>
              <UiComponentProvider>
                <Header />
                <div className="overflow-hidden">{children}</div>
                <Footer />
              </UiComponentProvider>
            </DarkThemeProvider>
          </AuthContextProviders>
        </TanstackQueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
